/**
 * CSS Build Script
 *
 * Concatenates all CSS files from src/styles/ into the root styles.css
 * Run with: node scripts/build-css.js
 */

const fs = require('fs');
const path = require('path');

const STYLES_DIR = path.join(__dirname, '..', 'src', 'styles');
const OUTPUT_FILE = path.join(__dirname, '..', 'styles.css');

// Header warning for the generated file
const HEADER = `/**
 * Spicy Tools Styles
 *
 * AUTO-GENERATED FILE - DO NOT EDIT DIRECTLY
 *
 * This file is automatically generated from source files in src/styles/
 * To modify styles, edit the source files and run: npm run build:css
 *
 * Generated: ${new Date().toISOString()}
 */

`;

function buildCSS() {
    // Get all CSS files from src/styles/
    const files = fs.readdirSync(STYLES_DIR)
        .filter(file => file.endsWith('.css'))
        .sort(); // Alphabetical order for consistency

    if (files.length === 0) {
        console.log('No CSS files found in src/styles/');
        return;
    }

    console.log(`Building CSS from ${files.length} source file(s)...`);

    let output = HEADER;

    for (const file of files) {
        const filePath = path.join(STYLES_DIR, file);
        const content = fs.readFileSync(filePath, 'utf8');

        // Add section header
        output += `/* ============================================\n`;
        output += ` * ${file}\n`;
        output += ` * ============================================ */\n\n`;
        output += content.trim();
        output += '\n\n';

        console.log(`  + ${file}`);
    }

    // Write the concatenated output
    fs.writeFileSync(OUTPUT_FILE, output.trim() + '\n');
    console.log(`\nWritten to: styles.css`);
}

buildCSS();
